### ISSUE TITLE
`eth` 0.5 tracker

### ISSUE THREAD

**Issue by q9f** [se3000/ruby-eth#68]
ultimate goals:
- long-term support for ruby 3.0+
- reduce external dependencies of unmaintained and abandoned gems
- move all crypto dependencies to native ruby if possible (secp256k1, openssl) to ensure no breakage by OS

essential components
- [x] keys pairs, accounts 
  - [x] https://github.com/etscrivner/rbsecp256k1
  - [x] addresses, checksums (eip 55)
  - [x] encryption, decryption
  - [x] sign, verify/recover
  - [ ] hd wallets (money tree?)
- [x] rlp encoding/decoding
  - [x] https://github.com/cryptape/ruby-rlp (archived? fork?)
- [x] transaction composition, signing, and verification
  - [x] chain ID, replay protection (eip 155)
  - [x] types, envelopes (eip 2718, eip 1599)
- [x] message signatures and recovery (raw messages and structured signatures)
  - [x] typed structured data hashing and signing (eip 712)
- [x] implement ethereum tests where applicable https://github.com/ethereum/tests

constraints
- [x] spec-driven, 100% coverage
- [x] fully documented (auto-generate HTML docs)
- [x] ruby-first, low-dependencies, if possible

considerations
- [ ] cherry-pick ethereum.rb features or consider merging both gems https://github.com/EthWorks/ethereum.rb
  - [x] client, http client, ws client
  - [ ] contracts (?)
